"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 🌟 문지기 위치 완벽함!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'capstone_db',       # 방금 성공적으로 만들어진 DB 이름
        'USER': 'root',              # MySQL 접속 아이디 (보통 root)
        'PASSWORD': os.environ.get('DB_PASSWORD'), # ⬅️ 꼭 본인 비밀번호로 바꿔주세요!
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# 🌟 (추가) CORS 허용 설정
CORS_ALLOW_ALL_ORIGINS = True  # 현재는 캡스톤 개발 단계이므로 모든 주소의 접근을 시원하게 허용!
CORS_ALLOW_CREDENTIALS = True


# 🚀 DRF 프레임워크에게 "이제부터 API 설명서는 spectacular가 만든다!" 라고 선언
# 🚀 DRF 프레임워크 설정 모음
REST_FRAMEWORK = {
    # 1. 아까 추가했던 Swagger 메뉴판 설정
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # ==========================================
    # 🛡️ 2. 신규 추가: 철벽 방어막 (Throttling) 설정
    # ==========================================
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # 로그인 안 한(익명) 해커 차단용
        'rest_framework.throttling.UserRateThrottle', # 로그인 한 유저 차단용
    ],
    'DEFAULT_THROTTLE_RATES': {
        # 넉넉하게 1분에 60번 (1초에 1번 꼴) 허용으로 수정!
        'anon': '60/minute', 
        'user': '1000/day', 
    }
}
# 📖 메뉴판(Swagger) 표지 꾸미기
SPECTACULAR_SETTINGS = {
    'TITLE': '카페 재고 및 매출 예측 API',
    'DESCRIPTION': '프론트엔드 데이터 연동을 위한 백엔드 API 명세서 및 테스트 페이지입니다.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}