# Generated by Django 6.0.3 on 2026-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_weather_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleshistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='sale_datetime',
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='category',
            field=models.CharField(default='기타', max_length=50),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='product_name',
            field=models.CharField(default='미정', max_length=100),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='region',
            field=models.CharField(default='서울', max_length=20),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='sale_date',
            field=models.CharField(default='20260101', max_length=8),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
