# Generated by Django 6.0.3 on 2026-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_saleshistory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='pty_code',
            field=models.IntegerField(default=0, verbose_name='강수형태(PTY)'),
        ),
    ]
