# Generated by Django 6.0.3 on 2026-05-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_weather_pty_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_datetime', models.DateTimeField(auto_now_add=True, verbose_name='실행 일시')),
                ('weather_factors', models.CharField(blank=True, max_length=255, verbose_name='날씨 변수')),
                ('event_factors', models.CharField(blank=True, max_length=255, verbose_name='이벤트 변수')),
                ('impact_summary', models.CharField(max_length=255, verbose_name='영향 요약')),
            ],
        ),
    ]
