# Generated by Django 6.0.3 on 2026-03-23 07:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFactor',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='날짜')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='평균 기온')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='강수량')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='공휴일 여부')),
                ('has_promotion', models.BooleanField(default=False, verbose_name='프로모션 여부')),
                ('local_event', models.BooleanField(default=False, verbose_name='지역 행사 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='품목 코드')),
                ('name', models.CharField(max_length=100, verbose_name='품목명')),
                ('category', models.CharField(max_length=50, verbose_name='분류')),
                ('selling_price', models.IntegerField(verbose_name='판매 단가')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='공급업체명')),
                ('lead_time_days', models.IntegerField(verbose_name='입고 소요 기간(일)')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='권고 생성 일시')),
                ('recommended_qty', models.IntegerField(verbose_name='권장 발주량')),
                ('priority', models.CharField(choices=[('HIGH', '필수'), ('MEDIUM', '권장'), ('LOW', '여유')], max_length=20, verbose_name='우선순위')),
                ('estimated_cost', models.IntegerField(verbose_name='예상 발주 금액')),
                ('reason', models.TextField(verbose_name='권고 사유')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='품목')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(verbose_name='입고일자')),
                ('expiration_date', models.DateField(verbose_name='유통기한 만료일자')),
                ('current_qty', models.IntegerField(verbose_name='현재 수량')),
                ('status', models.CharField(choices=[('NORMAL', '정상'), ('EMPTY', '소진'), ('DISCARDED', '폐기')], default='NORMAL', max_length=20, verbose_name='상태')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='품목')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='예측 실행 일시')),
                ('target_date', models.DateField(verbose_name='예측 대상 일자')),
                ('predicted_qty', models.FloatField(verbose_name='예상 판매량')),
                ('forecast_period', models.IntegerField(choices=[(1, '1일'), (2, '2일'), (7, '7일'), (30, '30일')], verbose_name='예측 기간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='품목')),
            ],
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='판매 일시')),
                ('quantity', models.IntegerField(verbose_name='판매 수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='품목')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.IntegerField(verbose_name='도매 단가')),
                ('min_order_qty', models.IntegerField(verbose_name='최소 발주 수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='품목')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='공급업체')),
            ],
        ),
        migrations.CreateModel(
            name='WasteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='폐기 일시')),
                ('quantity', models.IntegerField(verbose_name='폐기 수량')),
                ('reason', models.CharField(max_length=255, verbose_name='폐기 사유')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorybatch', verbose_name='폐기된 배치')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='품목')),
            ],
        ),
    ]
