# Generated by Django 6.0.3 on 2026-04-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.CharField(max_length=8, verbose_name='예보날짜')),
                ('base_time', models.CharField(max_length=4, verbose_name='예보시간')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='온도(℃)')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='강수량(mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
