# Generated by Django 6.0.3 on 2026-04-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='region',
            field=models.CharField(default='서울', max_length=20, verbose_name='지역'),
        ),
    ]
